name: generate animation
on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: generate github-user-contribution.svg
        uses: Platane/snk@master
        with:
          github_user_name: sathviksaya
          svg_out_path: dist/github-user-contribution.svg
      - name: push github-user-contribution.svg to the main branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
